# used to easily develop services
# run using ./dev.sh in parent folder

services:
  app-proxy:
    image: nginx:latest
    ports:
      - 3000:80
    volumes:
      - ./infrastructure/kubernetes/proxy.yaml:/etc/nginx/proxy.yaml
    networks:
      - soat7-network
    command:
      - /bin/sh
      - -c
      - |
        sed '7,30!d' etc/nginx/proxy.yaml > etc/nginx/nginx.conf
        sed -i "s@resolver kube@resolver 127.0.0.11; # &@" etc/nginx/nginx.conf
        sed -i "s@.vehicle-app.svc.cluster.local@@" etc/nginx/nginx.conf
        cat etc/nginx/nginx.conf
        nginx -g "daemon off;"

  app-svc-vehicle:
    image: node:20-alpine3.18
    ports:
      - 3001:80
      - 9779:9779
    working_dir: /app
    environment:
      - NODE_ENV=development
      - TZ=America/Sao_Paulo
    env_file:
      - ../ms-vehicle/.env.sample
    volumes:
      - ./ms-vehicle:/app
      - /app/node_modules/
    networks:
      - soat7-network
    depends_on:
      - db-svc-mongo
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run prebuild
        npm run start:debug

  db-svc-mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=team75
      - MONGO_INITDB_ROOT_PASSWORD=FIAP#Team75
    ports:
      - 27017:27017
    volumes:
      - ./infrastructure/.data/mongo:/data/db
    networks: 
      - soat7-network

networks:
  soat7-network:
    driver: bridge
